trigger:
- master

variables:
  backendServiceArm: 'Visual Studio Enterprise(17b12858-3960-4e6f-a663-a06fdae23428)'
  backendAzureRmResourceGroupName: 'resourcegroup-tfstate'
  backendAzureRmStorageAccountName: 'terraformtfstateskip'
  backendAzureRmContainerName: 'tfstate'
  location: 'westeurope'
  tfBackendEnvironment: terraform_backend_tfstate
  devEnvironment: dev
  testEnvironment: test
  prodEnvironment: prod

stages:
- template: template-create-terraform-backend.yml
  parameters:
    environment: $(tfBackendEnvironment)
    environmentDisplayName: Create Terraform Backend

- template: template-terraform-stages.yml
  parameters:
    environment: $(devEnvironment)
    environmentDisplayName: Development
    backendAzureRmKey: $(devEnvironment).tfstate
    dependsOn: [$(tfBackendEnvironment)]

- template: template-terraform-stages.yml
  parameters:
    environment: $(testEnvironment)
    environmentDisplayName: Test
    backendAzureRmKey: $(testEnvironment).tfstate
    dependsOn: [$(tfBackendEnvironment)]

- template: template-terraform-stages.yml
  parameters:
    environment: $(prodEnvironment)
    environmentDisplayName: Production
    backendAzureRmKey: $(prodEnvironment).tfstate
    dependsOn: ['${{ variables.tfBackendEnvironment }}', '${{ variables.devEnvironment }}', '${{ variables.testEnvironment }}']
