trigger:
- master

variables:
  backendServiceArm: 'Visual Studio Enterprise(17b12858-3960-4e6f-a663-a06fdae23428)'
  backendAzureRmResourceGroupName: 'resourcegroup-tfstate'
  backendAzureRmStorageAccountName: 'terraformtfstateskip'
  backendAzureRmContainerName: 'tfstate'
  location: 'westeurope'

stages:
- template: template-create-terraform-backend.yml
  

- template: template-terraform-stages.yml
  parameters:
    environment: dev
    environmentDisplayName: Development
    backendAzureRmKey: 'dev.tfstate'

- template: template-terraform-stages.yml
  dependsOn: Terraform_Backend
  parameters:
    environment: test
    environmentDisplayName: Test
    backendAzureRmKey: 'test.tfstate'

- template: template-terraform-stages.yml
  parameters:
    environment: prod
    environmentDisplayName: Production
    backendAzureRmKey: 'prod.tfstate'
