trigger:
- master

variables:
  backendServiceArm: 'Visual Studio Enterprise(17b12858-3960-4e6f-a663-a06fdae23428)'
  backendAzureRmResourceGroupName: 'resourcegroup-tfstate'
  backendAzureRmStorageAccountName: 'terraformtfstateskip'
  backendAzureRmContainerName: 'tfstate'
  location: 'westeurope'
  tfInitBackend: terraform_backend_tfstate
  devEnvironment: dev
  testEnvironment: test
  prodEnvironment: prod

stages:
# stage named Terraform_Backend
- template: template-create-terraform-backend.yml
  parameters:
    environment: $(tfInitBackend)
    environmentDisplayName: Create Terraform Backend to Save State

- template: template-terraform-stages.yml
  parameters:
    environment: ${{ variables.devEnvironment }}
    environmentDisplayName: Development
    backendAzureRmKey: $(devEnvironment).tfstate
    dependsOn: [Terraform_Backend]

- template: template-terraform-stages.yml
  parameters:
    environment: ${{ variables.testEnvironment }}
    environmentDisplayName: Test
    backendAzureRmKey: $(testEnvironment).tfstate
    dependsOn: [Terraform_Backend]

- template: template-terraform-stages.yml
  parameters:
    environment: ${{ variables.prodEnvironment }}
    environmentDisplayName: Production
    backendAzureRmKey: $(prodEnvironment).tfstate
    dependsOn: [Terraform_Backend, '${{ variables.devEnvironment }}', '${{ variables.testEnvironment }}']
