trigger:
- master

variables:
  backendServiceArm: 'Visual Studio Enterprise(17b12858-3960-4e6f-a663-a06fdae23428)'
  backendAzureRmResourceGroupName: 'resourcegroup-tfstate'
  backendAzureRmStorageAccountName: 'terraformtfstate'
  backendAzureRmContainerName: 'tfstate'
  location: 'westeurope'
  tfBackendEnvironment: tf_backend
  devEnvironment: dev
  testEnvironment: test
  prodEnvironment: prod

stages:
- template: template-create-terraform-backend.yml
  parameters:
    environment: ${{ variables.tfBackendEnvironment }}
    environmentDisplayName: Create TF Backend
    dependsOn: []

- template: template-terraform-stages.yml
  parameters:
    environment: ${{ variables.devEnvironment }}
    environmentDisplayName: Development
    backendAzureRmKey: $(devEnvironment).tfstate
    dependsOn: ['${{ variables.tfBackendEnvironment }}']

- template: template-terraform-stages.yml
  parameters:
    environment: ${{ variables.testEnvironment }}
    environmentDisplayName: Test
    backendAzureRmKey: $(testEnvironment).tfstate
    dependsOn: ['${{ variables.tfBackendEnvironment }}']

- template: template-terraform-stages.yml
  parameters:
    environment: ${{ variables.prodEnvironment }}
    environmentDisplayName: Production
    backendAzureRmKey: $(prodEnvironment).tfstate
    dependsOn: ['${{ variables.tfBackendEnvironment }}', '${{ variables.devEnvironment }}', '${{ variables.testEnvironment }}']
