trigger:
- master

variables:
  backendServiceArm: 'Visual Studio Enterprise(17b12858-3960-4e6f-a663-a06fdae23428)'
  backendAzureRmResourceGroupName: 'resourcegroup-tfstate'
  backendAzureRmStorageAccountName: 'terraformtfstateskip'
  backendAzureRmContainerName: 'tfstate'
  location: 'westeurope'
  devEnvironment: dev
  testEnvironment: test
  prodEnvironment: prod

stages:
# stage named Terraform_Backend
- template: template-create-terraform-backend.yml

# stage named Terraform_${{ parameters.devEnvironment }}
- template: template-terraform-stages.yml
  parameters:
    environment: ${{ variables.devEnvironment }}
    environmentDisplayName: Development
    backendAzureRmKey: $(devEnvironment).tfstate
    dependsOn: [Terraform_Backend]

- template: template-terraform-stages.yml
  parameters:
    environment: ${{ variables.testEnvironment }}
    environmentDisplayName: Test
    backendAzureRmKey: $(testEnvironment).tfstate
    dependsOn: [Terraform_Backend]

- template: template-terraform-stages.yml
  parameters:
    environment: ${{ variables.prodEnvironment }}
    environmentDisplayName: Production
    backendAzureRmKey: $(devEnvironment).tfstate
    dependsOn: [Terraform_Backend, ${{ variables.devEnvironment }}, ${{ variables.testEnvironment }}]
